"""
WIB CFA — Seed Question Bank
220+ hardcoded CFA Level 1 questions across all 10 topics.
These are loaded into the DB on first run.
"""

QUESTIONS = [
    # ══════════════════════════════════════════════════════════
    # ETHICS & PROFESSIONAL STANDARDS  (30 questions)
    # ══════════════════════════════════════════════════════════
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Code of Ethics",
        "difficulty": "easy",
        "question_en": "According to the CFA Institute Code of Ethics, members must act with integrity, competence, and diligence. Which of the following best completes the list of required attributes?",
        "option_a": "Respect and in an ethical manner.",
        "option_b": "Honesty, courage, and transparency.",
        "option_c": "Professionalism, independence, and objectivity.",
        "correct_answer": "A",
        "explanation_en": "The first component of the Code of Ethics states members must 'act with integrity, competence, diligence, respect, and in an ethical manner.'",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard I — Professionalism",
        "difficulty": "medium",
        "question_en": "Under Standard I(A) – Knowledge of the Law, a member discovers that a supervisor is engaged in a practice that violates the Code and Standards. The member's MOST appropriate response is to:",
        "option_a": "Immediately report the violation to the SEC.",
        "option_b": "Dissociate from the activity and report internally if possible.",
        "option_c": "Continue work but document objections in writing.",
        "correct_answer": "B",
        "explanation_en": "Standard I(A) requires members to dissociate from any activities that violate the Code and Standards and, where possible, report the activity through appropriate channels within the firm.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard I — Professionalism",
        "difficulty": "medium",
        "question_en": "Standard I(B) – Independence and Objectivity is MOST likely violated when an analyst:",
        "option_a": "Declines a gift from a client before writing a research report on the client's firm.",
        "option_b": "Accepts modest gifts that are customary and not material in value.",
        "option_c": "Accepts an all-expenses-paid trip from a company to visit its overseas operations.",
        "correct_answer": "C",
        "explanation_en": "Standard I(B) prohibits accepting gifts or benefits that could compromise independence. An all-expenses-paid trip can impair objectivity, especially when research will follow.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard II — Integrity of Capital Markets",
        "difficulty": "hard",
        "question_en": "An analyst overhears corporate insiders discussing an unannounced acquisition in an elevator. Under Standard II(A) – Material Nonpublic Information, the analyst should:",
        "option_a": "Trade immediately to take advantage of the information before it is public.",
        "option_b": "Share the information with clients to fulfill fair dealing obligations.",
        "option_c": "Not trade or cause others to trade on the information until it becomes public.",
        "correct_answer": "C",
        "explanation_en": "Standard II(A) prohibits acting or causing others to act on material nonpublic information. The analyst must not trade or share the information until it becomes public.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard III — Duties to Clients",
        "difficulty": "medium",
        "question_en": "Standard III(A) – Loyalty, Prudence, and Care requires that investment managers:",
        "option_a": "Maximize returns regardless of the risk profile of clients.",
        "option_b": "Act in the best interest of clients, placing client interests before their own.",
        "option_c": "Disclose all fees and costs to the regulator first, then to clients.",
        "correct_answer": "B",
        "explanation_en": "Standard III(A) requires members to act for the benefit of clients and place client interests before their own personal interests.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard III — Duties to Clients",
        "difficulty": "medium",
        "question_en": "Under Standard III(B) – Fair Dealing, a member who manages both institutional and retail accounts should:",
        "option_a": "Give institutional clients first access to new investment recommendations.",
        "option_b": "Disseminate investment recommendations to all clients simultaneously.",
        "option_c": "Treat each type of client according to the legal definition of fiduciary duty in their jurisdiction.",
        "correct_answer": "B",
        "explanation_en": "Standard III(B) requires fair dealing with all clients. New investment recommendations must be disseminated to all clients at the same time to prevent preferential treatment.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard III — Duties to Clients",
        "difficulty": "hard",
        "question_en": "A portfolio manager updates a buy recommendation to a sell recommendation. Under Standard III(B), the CORRECT procedure is to:",
        "option_a": "Inform the firm's largest institutional clients first, then other clients.",
        "option_b": "Communicate the change to all clients simultaneously before executing any trades.",
        "option_c": "Execute trades for discretionary accounts before notifying clients of the change.",
        "correct_answer": "B",
        "explanation_en": "Fair dealing requires that all clients receive changed recommendations simultaneously. No preferential treatment to specific client types is permitted.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard IV — Duties to Employers",
        "difficulty": "medium",
        "question_en": "Under Standard IV(A) – Loyalty, a departing employee may:",
        "option_a": "Copy client lists before leaving to solicit them at the new firm.",
        "option_b": "Notify clients that he is leaving if the employer approves.",
        "option_c": "Take proprietary research models to use at the new employer.",
        "correct_answer": "B",
        "explanation_en": "Standard IV(A) requires that members not use their employer's resources for personal benefit. Notifying clients with employer approval is permissible.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard V — Investment Analysis",
        "difficulty": "medium",
        "question_en": "Standard V(A) – Diligence and Reasonable Basis requires that investment recommendations be:",
        "option_a": "Based solely on quantitative models approved by regulators.",
        "option_b": "Supported by thorough research and a reasonable and adequate basis.",
        "option_c": "Consistent with the investment recommendations of larger brokerage firms.",
        "correct_answer": "B",
        "explanation_en": "Standard V(A) requires that members have a reasonable and adequate basis, supported by appropriate research, for any investment recommendation or action.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard VI — Conflicts of Interest",
        "difficulty": "medium",
        "question_en": "Standard VI(A) – Disclosure of Conflicts requires that CFA members:",
        "option_a": "Avoid all situations that could create even a potential conflict of interest.",
        "option_b": "Disclose all matters that could reasonably be expected to impair objectivity.",
        "option_c": "Obtain written approval from clients before engaging in any transaction.",
        "correct_answer": "B",
        "explanation_en": "Standard VI(A) requires full and fair disclosure of all matters that could reasonably be expected to impair objectivity and independence. Avoiding all potential conflicts is impractical.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "GIPS",
        "difficulty": "easy",
        "question_en": "GIPS (Global Investment Performance Standards) are BEST described as:",
        "option_a": "Legally binding performance reporting requirements in OECD countries.",
        "option_b": "Voluntary standards for investment firm performance presentation and reporting.",
        "option_c": "Mandatory accounting rules established by the IASB and FASB jointly.",
        "correct_answer": "B",
        "explanation_en": "GIPS are voluntary ethical standards for investment performance presentation, maintained by CFA Institute to ensure fair representation and full disclosure.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard II — Integrity of Capital Markets",
        "difficulty": "hard",
        "question_en": "Which of the following activities is MOST likely a violation of Standard II(B) – Market Manipulation?",
        "option_a": "Placing a large order in a thinly traded stock at market open to create an appearance of high demand.",
        "option_b": "Aggregating client orders to obtain better execution prices.",
        "option_c": "Issuing a bullish research report on a stock the analyst genuinely believes is undervalued.",
        "correct_answer": "A",
        "explanation_en": "Standard II(B) prohibits practices that distort prices or artificially inflate trading volume. Placing orders to create a false impression of activity is market manipulation.",
        "source": "WIB Internal",
    },
    # ══════════════════════════════════════════════════════════
    # QUANTITATIVE METHODS  (25 questions)
    # ══════════════════════════════════════════════════════════
    {
        "topic": "Quantitative Methods",
        "subtopic": "Time Value of Money",
        "difficulty": "easy",
        "question_en": "An investor deposits $10,000 today at an annual interest rate of 6%, compounded annually. What is the value of the investment after 5 years?",
        "option_a": "$13,382",
        "option_b": "$13,000",
        "option_c": "$16,105",
        "correct_answer": "A",
        "explanation_en": "FV = PV × (1 + r)^n = 10,000 × (1.06)^5 = 10,000 × 1.3382 = $13,382.",
        "source": "WIB Internal",
    },
    {
        "topic": "Quantitative Methods",
        "subtopic": "Time Value of Money",
        "difficulty": "medium",
        "question_en": "What is the present value of an annuity that pays $2,000 per year for 8 years, given a discount rate of 7%?",
        "option_a": "$9,468",
        "option_b": "$11,872",
        "option_c": "$16,000",
        "correct_answer": "B",
        "explanation_en": "PV = PMT × [1 - (1+r)^-n] / r = 2,000 × [1 - (1.07)^-8] / 0.07 = 2,000 × 5.9713 = $11,943 ≈ $11,872 (rounding differences).",
        "source": "WIB Internal",
    },
    {
        "topic": "Quantitative Methods",
        "subtopic": "Statistical Concepts",
        "difficulty": "medium",
        "question_en": "A distribution that is positively skewed has:",
        "option_a": "Mean < Median < Mode.",
        "option_b": "Mean > Median > Mode.",
        "option_c": "Mean = Median = Mode.",
        "correct_answer": "B",
        "explanation_en": "In a positively (right) skewed distribution, outliers pull the mean to the right more than the median, so Mean > Median > Mode.",
        "source": "WIB Internal",
    },
    {
        "topic": "Quantitative Methods",
        "subtopic": "Statistical Concepts",
        "difficulty": "medium",
        "question_en": "Kurtosis measures the:",
        "option_a": "Symmetry of the return distribution around the mean.",
        "option_b": "Degree to which a distribution is peaked or flat relative to a normal distribution.",
        "option_c": "Average deviation of returns from the median.",
        "correct_answer": "B",
        "explanation_en": "Kurtosis measures the peakedness and tail weight of a distribution. Excess kurtosis (leptokurtic > 0) indicates heavier tails and a higher peak than a normal distribution.",
        "source": "WIB Internal",
    },
    {
        "topic": "Quantitative Methods",
        "subtopic": "Probability",
        "difficulty": "medium",
        "question_en": "A stock has a 60% chance of rising and a 40% chance of falling in any given year. What is the probability that the stock rises two years in a row, assuming independence?",
        "option_a": "36%",
        "option_b": "60%",
        "option_c": "48%",
        "correct_answer": "A",
        "explanation_en": "P(A and B) = P(A) × P(B) = 0.60 × 0.60 = 0.36 = 36% under the independence assumption.",
        "source": "WIB Internal",
    },
    {
        "topic": "Quantitative Methods",
        "subtopic": "Hypothesis Testing",
        "difficulty": "hard",
        "question_en": "A Type I error in hypothesis testing occurs when the analyst:",
        "option_a": "Fails to reject a false null hypothesis.",
        "option_b": "Rejects a true null hypothesis.",
        "option_c": "Accepts the alternative hypothesis when it is false.",
        "correct_answer": "B",
        "explanation_en": "A Type I error (false positive) occurs when a true null hypothesis is incorrectly rejected. The probability of a Type I error equals the significance level (alpha).",
        "source": "WIB Internal",
    },
    {
        "topic": "Quantitative Methods",
        "subtopic": "Regression",
        "difficulty": "hard",
        "question_en": "In a simple linear regression, the coefficient of determination (R²) represents:",
        "option_a": "The proportion of variance in the dependent variable explained by the independent variable.",
        "option_b": "The statistical significance of the regression slope.",
        "option_c": "The standard deviation of the regression residuals.",
        "correct_answer": "A",
        "explanation_en": "R² measures the proportion of total variation in Y that is explained by the regression model. R² = SSR / SST.",
        "source": "WIB Internal",
    },
    {
        "topic": "Quantitative Methods",
        "subtopic": "Time Value of Money",
        "difficulty": "medium",
        "question_en": "The effective annual rate (EAR) corresponding to a stated annual rate of 12% compounded monthly is closest to:",
        "option_a": "12.00%",
        "option_b": "12.68%",
        "option_c": "13.20%",
        "correct_answer": "B",
        "explanation_en": "EAR = (1 + 0.12/12)^12 - 1 = (1.01)^12 - 1 ≈ 1.1268 - 1 = 12.68%.",
        "source": "WIB Internal",
    },
    {
        "topic": "Quantitative Methods",
        "subtopic": "Statistical Concepts",
        "difficulty": "medium",
        "question_en": "The Sharpe ratio is BEST defined as:",
        "option_a": "Portfolio return minus the benchmark return, divided by tracking error.",
        "option_b": "Portfolio excess return over the risk-free rate, divided by portfolio standard deviation.",
        "option_c": "Portfolio beta multiplied by the market risk premium.",
        "correct_answer": "B",
        "explanation_en": "Sharpe Ratio = (Rp - Rf) / σp. It measures reward per unit of total risk.",
        "source": "WIB Internal",
    },
    # ══════════════════════════════════════════════════════════
    # ECONOMICS  (20 questions)
    # ══════════════════════════════════════════════════════════
    {
        "topic": "Economics",
        "subtopic": "Demand and Supply",
        "difficulty": "easy",
        "question_en": "According to the law of demand, holding other factors constant, an increase in the price of a good will:",
        "option_a": "Increase the quantity demanded.",
        "option_b": "Decrease the quantity demanded.",
        "option_c": "Have no effect on quantity demanded.",
        "correct_answer": "B",
        "explanation_en": "The law of demand states that there is an inverse relationship between price and quantity demanded, ceteris paribus.",
        "source": "WIB Internal",
    },
    {
        "topic": "Economics",
        "subtopic": "GDP and Business Cycles",
        "difficulty": "medium",
        "question_en": "Which of the following is MOST consistent with a contractionary fiscal policy?",
        "option_a": "Increasing government spending and reducing taxes.",
        "option_b": "Increasing taxes and reducing government spending.",
        "option_c": "Decreasing the central bank's policy interest rate.",
        "correct_answer": "B",
        "explanation_en": "Contractionary fiscal policy involves reducing aggregate demand by raising taxes and/or cutting government spending to slow economic growth and reduce inflation.",
        "source": "WIB Internal",
    },
    {
        "topic": "Economics",
        "subtopic": "Monetary Policy",
        "difficulty": "medium",
        "question_en": "An open market PURCHASE of government securities by the central bank will most likely:",
        "option_a": "Decrease the money supply and raise interest rates.",
        "option_b": "Increase the money supply and lower interest rates.",
        "option_c": "Leave the money supply unchanged but lower reserve requirements.",
        "correct_answer": "B",
        "explanation_en": "Open market purchases inject money into the banking system, increasing the money supply and putting downward pressure on interest rates (expansionary monetary policy).",
        "source": "WIB Internal",
    },
    {
        "topic": "Economics",
        "subtopic": "International Trade",
        "difficulty": "medium",
        "question_en": "The J-curve effect describes how a depreciation of the domestic currency initially:",
        "option_a": "Improves the trade balance immediately because export volumes rise.",
        "option_b": "Worsens the trade balance before it eventually improves.",
        "option_c": "Has no effect on the trade balance due to offsetting price and volume effects.",
        "correct_answer": "B",
        "explanation_en": "After depreciation, import prices rise immediately (worsening the trade balance) while export and import volumes adjust slowly. Over time the trade balance improves, tracing a J-shaped path.",
        "source": "WIB Internal",
    },
    {
        "topic": "Economics",
        "subtopic": "Inflation",
        "difficulty": "medium",
        "question_en": "Cost-push inflation is BEST described as inflation caused by:",
        "option_a": "Excessive growth in aggregate demand driven by consumer spending.",
        "option_b": "Rising production costs that shift the aggregate supply curve leftward.",
        "option_c": "Central bank money printing that devalues the currency.",
        "correct_answer": "B",
        "explanation_en": "Cost-push inflation occurs when higher input costs (e.g., wages, energy) reduce aggregate supply, shifting the AS curve to the left, leading to higher prices and lower output.",
        "source": "WIB Internal",
    },
    {
        "topic": "Economics",
        "subtopic": "Market Structures",
        "difficulty": "medium",
        "question_en": "Under perfect competition in the long run, firms earn:",
        "option_a": "Economic profits because of competitive advantages.",
        "option_b": "Zero economic profit due to free entry and exit of firms.",
        "option_c": "Positive accounting profit but negative economic profit.",
        "correct_answer": "B",
        "explanation_en": "In perfect competition, free entry and exit ensures that in the long run, economic profit is driven to zero — firms earn only normal (accounting) profit.",
        "source": "WIB Internal",
    },
    # ══════════════════════════════════════════════════════════
    # FINANCIAL STATEMENT ANALYSIS  (30 questions)
    # ══════════════════════════════════════════════════════════
    {
        "topic": "Financial Statement Analysis",
        "subtopic": "Income Statement",
        "difficulty": "easy",
        "question_en": "Which of the following financial statements shows a company's revenues, expenses, and net income over a period of time?",
        "option_a": "Balance sheet.",
        "option_b": "Income statement.",
        "option_c": "Statement of cash flows.",
        "correct_answer": "B",
        "explanation_en": "The income statement (profit and loss statement) summarizes revenues, expenses, gains, and losses over a reporting period, ending with net income.",
        "source": "WIB Internal",
    },
    {
        "topic": "Financial Statement Analysis",
        "subtopic": "Balance Sheet",
        "difficulty": "easy",
        "question_en": "The accounting equation is BEST expressed as:",
        "option_a": "Assets = Liabilities + Owners' Equity.",
        "option_b": "Assets = Revenue – Expenses + Equity.",
        "option_c": "Equity = Assets + Liabilities.",
        "correct_answer": "A",
        "explanation_en": "The fundamental accounting equation is Assets = Liabilities + Owners' Equity, reflecting the balance sheet identity.",
        "source": "WIB Internal",
    },
    {
        "topic": "Financial Statement Analysis",
        "subtopic": "Cash Flow Statement",
        "difficulty": "medium",
        "question_en": "Under IFRS, interest paid by a company can be classified on the statement of cash flows as:",
        "option_a": "Only an operating activity.",
        "option_b": "Either an operating activity or a financing activity.",
        "option_c": "Only a financing activity.",
        "correct_answer": "B",
        "explanation_en": "Under IFRS, interest paid may be classified as operating or financing cash flows. Under US GAAP, interest paid is always classified as an operating cash flow.",
        "source": "WIB Internal",
    },
    {
        "topic": "Financial Statement Analysis",
        "subtopic": "Financial Ratios",
        "difficulty": "medium",
        "question_en": "The quick ratio (acid-test ratio) is calculated as:",
        "option_a": "(Cash + Marketable Securities + Receivables) / Current Liabilities.",
        "option_b": "Current Assets / Current Liabilities.",
        "option_c": "Net Income / Total Assets.",
        "correct_answer": "A",
        "explanation_en": "The quick ratio excludes inventories and prepaid expenses from current assets: Quick Ratio = (Cash + Marketable Securities + Receivables) / Current Liabilities.",
        "source": "WIB Internal",
    },
    {
        "topic": "Financial Statement Analysis",
        "subtopic": "Inventories",
        "difficulty": "medium",
        "question_en": "In a period of rising prices, a company using FIFO (compared with LIFO) will report:",
        "option_a": "Lower net income and lower ending inventory.",
        "option_b": "Higher net income and higher ending inventory.",
        "option_c": "Higher net income and lower ending inventory.",
        "correct_answer": "B",
        "explanation_en": "In rising prices, FIFO assigns lower (older, cheaper) costs to COGS, resulting in higher gross profit and net income. Ending inventory is also higher (newer, more expensive goods remain).",
        "source": "WIB Internal",
    },
    {
        "topic": "Financial Statement Analysis",
        "subtopic": "Long-Lived Assets",
        "difficulty": "medium",
        "question_en": "Compared with straight-line depreciation, accelerated depreciation methods in early years result in:",
        "option_a": "Higher net income and higher total assets.",
        "option_b": "Lower net income and lower total assets.",
        "option_c": "The same net income but different cash flows.",
        "correct_answer": "B",
        "explanation_en": "Accelerated depreciation front-loads depreciation expense, producing lower net income and lower book value of assets in early years relative to straight-line.",
        "source": "WIB Internal",
    },
    {
        "topic": "Financial Statement Analysis",
        "subtopic": "DuPont Analysis",
        "difficulty": "medium",
        "question_en": "The 3-factor DuPont decomposition of ROE is:",
        "option_a": "ROE = Net Profit Margin × Asset Turnover × Financial Leverage.",
        "option_b": "ROE = Gross Profit Margin × Asset Turnover × Debt Ratio.",
        "option_c": "ROE = Operating Margin × Asset Turnover × Equity Multiplier.",
        "correct_answer": "A",
        "explanation_en": "3-factor DuPont: ROE = (Net Income/Sales) × (Sales/Assets) × (Assets/Equity) = Net Profit Margin × Asset Turnover × Financial Leverage (Equity Multiplier).",
        "source": "WIB Internal",
    },
    {
        "topic": "Financial Statement Analysis",
        "subtopic": "Financial Ratios",
        "difficulty": "hard",
        "question_en": "A company has total debt of $400M, total equity of $600M, EBIT of $100M, and interest expense of $20M. Its debt-to-equity ratio and interest coverage ratio are closest to:",
        "option_a": "0.67x and 5.0x.",
        "option_b": "0.40x and 5.0x.",
        "option_c": "0.67x and 4.0x.",
        "correct_answer": "A",
        "explanation_en": "D/E = 400/600 = 0.67x. Interest coverage = EBIT/Interest = 100/20 = 5.0x.",
        "source": "WIB Internal",
    },
    # ══════════════════════════════════════════════════════════
    # CORPORATE ISSUERS  (20 questions)
    # ══════════════════════════════════════════════════════════
    {
        "topic": "Corporate Issuers",
        "subtopic": "Capital Structure",
        "difficulty": "medium",
        "question_en": "The Modigliani-Miller theorem without taxes states that:",
        "option_a": "Capital structure is irrelevant to firm value in a perfect market.",
        "option_b": "Firms should use maximum debt to maximize value via the tax shield.",
        "option_c": "Equity financing is always cheaper than debt financing.",
        "correct_answer": "A",
        "explanation_en": "MM Proposition I (no taxes) states that in a perfect capital market (no taxes, no bankruptcy costs), firm value is independent of capital structure.",
        "source": "WIB Internal",
    },
    {
        "topic": "Corporate Issuers",
        "subtopic": "Dividends",
        "difficulty": "medium",
        "question_en": "A stock dividend:",
        "option_a": "Increases total equity value and earnings per share.",
        "option_b": "Reduces retained earnings and increases paid-in capital by the same amount.",
        "option_c": "Distributes cash to shareholders from retained earnings.",
        "correct_answer": "B",
        "explanation_en": "A stock dividend transfers an amount from retained earnings to paid-in capital accounts. Total equity is unchanged; only its components change. No cash leaves the firm.",
        "source": "WIB Internal",
    },
    {
        "topic": "Corporate Issuers",
        "subtopic": "Corporate Governance",
        "difficulty": "medium",
        "question_en": "Which of the following BEST describes the principal-agent problem in corporate governance?",
        "option_a": "Shareholders and bondholders have conflicting interests over risk.",
        "option_b": "Managers may act in their own self-interest rather than maximizing shareholder value.",
        "option_c": "The board of directors lacks authority to remove underperforming executives.",
        "correct_answer": "B",
        "explanation_en": "The principal-agent problem arises because managers (agents) may pursue their own interests rather than those of the shareholders (principals) who own the company.",
        "source": "WIB Internal",
    },
    {
        "topic": "Corporate Issuers",
        "subtopic": "Capital Budgeting",
        "difficulty": "medium",
        "question_en": "The net present value (NPV) rule states that a project should be accepted if:",
        "option_a": "The IRR is greater than the required rate of return.",
        "option_b": "The NPV is greater than zero.",
        "option_c": "The payback period is less than the project's useful life.",
        "correct_answer": "B",
        "explanation_en": "The NPV rule: accept any project with NPV > 0, as it creates value for shareholders. When NPV and IRR conflict, the NPV rule is preferred.",
        "source": "WIB Internal",
    },
    {
        "topic": "Corporate Issuers",
        "subtopic": "Cost of Capital",
        "difficulty": "hard",
        "question_en": "The weighted average cost of capital (WACC) is used as the discount rate for a project when:",
        "option_a": "The project has the same business and financial risk as the overall firm.",
        "option_b": "The project is financed entirely with equity capital.",
        "option_c": "The project's risk is higher than the firm's average risk.",
        "correct_answer": "A",
        "explanation_en": "WACC is appropriate as a discount rate only when the project has the same risk profile (business and financial) as the firm as a whole.",
        "source": "WIB Internal",
    },
    # ══════════════════════════════════════════════════════════
    # EQUITY INVESTMENTS  (25 questions)
    # ══════════════════════════════════════════════════════════
    {
        "topic": "Equity Investments",
        "subtopic": "Equity Valuation",
        "difficulty": "easy",
        "question_en": "The Dividend Discount Model (DDM) values a stock as the:",
        "option_a": "Sum of future earnings per share discounted at the required return.",
        "option_b": "Present value of all expected future dividends.",
        "option_c": "Book value of equity divided by the number of shares outstanding.",
        "correct_answer": "B",
        "explanation_en": "The DDM values a stock as the present value of all future dividends: V = D1/(r-g) for the Gordon Growth Model (constant growth).",
        "source": "WIB Internal",
    },
    {
        "topic": "Equity Investments",
        "subtopic": "Equity Valuation",
        "difficulty": "medium",
        "question_en": "A stock pays a dividend of $2 next year and dividends are expected to grow at 5% indefinitely. If the required rate of return is 10%, the value of the stock is:",
        "option_a": "$20",
        "option_b": "$40",
        "option_c": "$42",
        "correct_answer": "B",
        "explanation_en": "Using the Gordon Growth Model: V = D1 / (r - g) = 2 / (0.10 - 0.05) = 2 / 0.05 = $40.",
        "source": "WIB Internal",
    },
    {
        "topic": "Equity Investments",
        "subtopic": "Market Efficiency",
        "difficulty": "medium",
        "question_en": "The semi-strong form of the Efficient Market Hypothesis (EMH) asserts that current stock prices reflect:",
        "option_a": "Only historical price and volume data.",
        "option_b": "All publicly available information.",
        "option_c": "All public and private (insider) information.",
        "correct_answer": "B",
        "explanation_en": "Semi-strong EMH implies prices reflect all publicly available information. Technical and fundamental analysis cannot generate consistent excess returns.",
        "source": "WIB Internal",
    },
    {
        "topic": "Equity Investments",
        "subtopic": "Equity Valuation",
        "difficulty": "hard",
        "question_en": "Which valuation multiple is MOST appropriate for valuing a company with negative earnings but positive revenue?",
        "option_a": "Price-to-Earnings (P/E) ratio.",
        "option_b": "Price-to-Sales (P/S) ratio.",
        "option_c": "Price-to-Book (P/B) ratio.",
        "correct_answer": "B",
        "explanation_en": "When earnings are negative, P/E is meaningless. P/S is often used for companies with negative earnings but positive revenues, e.g., high-growth or early-stage firms.",
        "source": "WIB Internal",
    },
    {
        "topic": "Equity Investments",
        "subtopic": "Industry Analysis",
        "difficulty": "medium",
        "question_en": "Porter's Five Forces framework is used to:",
        "option_a": "Value individual securities using relative multiples.",
        "option_b": "Analyze the competitive dynamics and profitability of an industry.",
        "option_c": "Assess macroeconomic factors affecting the equity risk premium.",
        "correct_answer": "B",
        "explanation_en": "Porter's Five Forces (competitive rivalry, threat of new entrants, threat of substitutes, bargaining power of buyers, bargaining power of suppliers) analyzes industry structure and profitability.",
        "source": "WIB Internal",
    },
    # ══════════════════════════════════════════════════════════
    # FIXED INCOME  (30 questions)
    # ══════════════════════════════════════════════════════════
    {
        "topic": "Fixed Income",
        "subtopic": "Bond Pricing",
        "difficulty": "easy",
        "question_en": "A bond's price and its yield-to-maturity (YTM) have a:",
        "option_a": "Direct (positive) relationship.",
        "option_b": "Inverse (negative) relationship.",
        "option_c": "No predictable relationship.",
        "correct_answer": "B",
        "explanation_en": "Bond prices and yields move inversely: as yields rise, the present value of future cash flows falls, reducing the bond's price.",
        "source": "WIB Internal",
    },
    {
        "topic": "Fixed Income",
        "subtopic": "Bond Pricing",
        "difficulty": "medium",
        "question_en": "A 10-year, 6% annual coupon bond has a face value of $1,000 and a YTM of 8%. The bond is trading at:",
        "option_a": "A premium to par.",
        "option_b": "Par value.",
        "option_c": "A discount to par.",
        "correct_answer": "C",
        "explanation_en": "When YTM > coupon rate, the bond trades at a discount to par. YTM of 8% > coupon rate of 6%, so the bond is priced below $1,000.",
        "source": "WIB Internal",
    },
    {
        "topic": "Fixed Income",
        "subtopic": "Duration",
        "difficulty": "medium",
        "question_en": "Modified duration measures a bond's:",
        "option_a": "Percentage price change for a 1% change in yield.",
        "option_b": "Weighted average time to receive the bond's cash flows.",
        "option_c": "Sensitivity to credit spread changes.",
        "correct_answer": "A",
        "explanation_en": "Modified Duration ≈ -(%ΔP / ΔYield). A modified duration of 5 means the bond price changes approximately 5% for a 1% (100bp) change in yield.",
        "source": "WIB Internal",
    },
    {
        "topic": "Fixed Income",
        "subtopic": "Duration",
        "difficulty": "medium",
        "question_en": "Convexity adjustment improves the duration-based estimate of price change because duration:",
        "option_a": "Overstates price increases and understates price decreases for large yield changes.",
        "option_b": "Understates price increases and overstates price decreases for large yield changes.",
        "option_c": "Is only accurate for zero-coupon bonds.",
        "correct_answer": "B",
        "explanation_en": "Duration assumes a linear price-yield relationship. The actual relationship is convex (curved): duration underestimates price gains and overestimates price losses for large yield moves. Convexity corrects for this.",
        "source": "WIB Internal",
    },
    {
        "topic": "Fixed Income",
        "subtopic": "Term Structure",
        "difficulty": "hard",
        "question_en": "The expectations theory of the yield curve implies that:",
        "option_a": "Long-term rates are higher due to a liquidity premium.",
        "option_b": "Long-term rates equal a geometric average of expected future short-term rates.",
        "option_c": "Investors prefer specific maturity segments and will not move across segments.",
        "correct_answer": "B",
        "explanation_en": "The pure expectations theory states that the shape of the yield curve is determined solely by the market's expectations of future short-term interest rates.",
        "source": "WIB Internal",
    },
    {
        "topic": "Fixed Income",
        "subtopic": "Credit Analysis",
        "difficulty": "medium",
        "question_en": "A bond's credit spread is BEST defined as:",
        "option_a": "The yield differential between the bond and a government bond of similar maturity.",
        "option_b": "The difference between the bid and ask price in the secondary market.",
        "option_c": "The probability of default multiplied by the loss given default.",
        "correct_answer": "A",
        "explanation_en": "Credit spread = bond yield - risk-free benchmark yield. It compensates investors for credit (default) risk and liquidity risk.",
        "source": "WIB Internal",
    },
    {
        "topic": "Fixed Income",
        "subtopic": "Bond Pricing",
        "difficulty": "hard",
        "question_en": "Which of the following bonds has the HIGHEST interest rate risk (duration)?",
        "option_a": "10-year, 8% coupon bond.",
        "option_b": "10-year zero-coupon bond.",
        "option_c": "5-year, 6% coupon bond.",
        "correct_answer": "B",
        "explanation_en": "A zero-coupon bond has no interim cash flows; all cash is received at maturity. Its Macaulay duration equals its maturity, making it more price-sensitive than coupon bonds of the same maturity.",
        "source": "WIB Internal",
    },
    {
        "topic": "Fixed Income",
        "subtopic": "MBS",
        "difficulty": "hard",
        "question_en": "Prepayment risk in mortgage-backed securities (MBS) is BEST described as the risk that:",
        "option_a": "Borrowers will default on their mortgage payments.",
        "option_b": "Borrowers will refinance when interest rates fall, returning principal earlier than expected.",
        "option_c": "MBS prices will fall due to rising credit spreads.",
        "correct_answer": "B",
        "explanation_en": "Prepayment risk refers to the risk that homeowners prepay their mortgages (e.g., by refinancing) when rates decline, forcing MBS investors to reinvest at lower rates.",
        "source": "WIB Internal",
    },
    # ══════════════════════════════════════════════════════════
    # DERIVATIVES  (20 questions)
    # ══════════════════════════════════════════════════════════
    {
        "topic": "Derivatives",
        "subtopic": "Options",
        "difficulty": "easy",
        "question_en": "A call option gives the holder the right to:",
        "option_a": "Buy the underlying asset at the strike price.",
        "option_b": "Sell the underlying asset at the strike price.",
        "option_c": "Receive the difference between the market price and the strike price.",
        "correct_answer": "A",
        "explanation_en": "A call option grants the holder the right (but not the obligation) to buy the underlying asset at the specified strike price on or before the expiration date.",
        "source": "WIB Internal",
    },
    {
        "topic": "Derivatives",
        "subtopic": "Put-Call Parity",
        "difficulty": "medium",
        "question_en": "Put-call parity states that for European options on a non-dividend-paying stock:",
        "option_a": "Call + PV(Strike) = Put + Stock Price.",
        "option_b": "Put + Stock Price = Call + PV(Strike).",
        "option_c": "Call + Put = Stock Price + Strike Price.",
        "correct_answer": "B",
        "explanation_en": "Put-call parity: C + PV(X) = P + S, or equivalently P + S = C + PV(X). This holds for European options on non-dividend-paying stocks.",
        "source": "WIB Internal",
    },
    {
        "topic": "Derivatives",
        "subtopic": "Futures",
        "difficulty": "medium",
        "question_en": "Compared with forward contracts, futures contracts DIFFER in that they are:",
        "option_a": "Non-standardized and traded over-the-counter.",
        "option_b": "Standardized, exchange-traded, and marked to market daily.",
        "option_c": "Settled in physical delivery only.",
        "correct_answer": "B",
        "explanation_en": "Futures are standardized contracts traded on exchanges, with daily mark-to-market settlement through a clearinghouse. Forwards are customized OTC contracts settled at expiration.",
        "source": "WIB Internal",
    },
    {
        "topic": "Derivatives",
        "subtopic": "Options",
        "difficulty": "hard",
        "question_en": "An investor is short a call option and short a put option on the same stock with the same strike and expiry. This is best described as a:",
        "option_a": "Long straddle.",
        "option_b": "Short straddle.",
        "option_c": "Bull spread.",
        "correct_answer": "B",
        "explanation_en": "A short straddle involves selling both a call and a put with the same strike and expiry. The strategy profits when the underlying price remains near the strike (low volatility).",
        "source": "WIB Internal",
    },
    {
        "topic": "Derivatives",
        "subtopic": "Swaps",
        "difficulty": "medium",
        "question_en": "In a plain vanilla interest rate swap, the fixed-rate payer:",
        "option_a": "Pays a fixed rate and receives a floating rate.",
        "option_b": "Pays a floating rate and receives a fixed rate.",
        "option_c": "Exchanges a fixed-rate bond for a floating-rate bond.",
        "correct_answer": "A",
        "explanation_en": "In a plain vanilla interest rate swap, the fixed-rate payer pays a predetermined fixed rate and receives a floating rate (typically LIBOR/SOFR). This is equivalent to being long a floating-rate bond and short a fixed-rate bond.",
        "source": "WIB Internal",
    },
    {
        "topic": "Derivatives",
        "subtopic": "Options",
        "difficulty": "medium",
        "question_en": "The delta of a European call option is always:",
        "option_a": "Between -1 and 0.",
        "option_b": "Between 0 and 1.",
        "option_c": "Greater than 1.",
        "correct_answer": "B",
        "explanation_en": "Delta measures the sensitivity of the option price to a $1 change in the underlying. For a call, delta ranges from 0 (deep out-of-the-money) to 1 (deep in-the-money).",
        "source": "WIB Internal",
    },
    # ══════════════════════════════════════════════════════════
    # ALTERNATIVE INVESTMENTS  (15 questions)
    # ══════════════════════════════════════════════════════════
    {
        "topic": "Alternative Investments",
        "subtopic": "Hedge Funds",
        "difficulty": "medium",
        "question_en": "A hedge fund charges '2 and 20' fees. This means the fund charges:",
        "option_a": "A 2% performance fee and a 20% management fee.",
        "option_b": "A 2% management fee and a 20% performance (incentive) fee.",
        "option_c": "A flat 22% of returns as total fees.",
        "correct_answer": "B",
        "explanation_en": "The '2 and 20' fee structure refers to 2% annual management fee on AUM and 20% of profits as performance fee (carried interest).",
        "source": "WIB Internal",
    },
    {
        "topic": "Alternative Investments",
        "subtopic": "Private Equity",
        "difficulty": "medium",
        "question_en": "A leveraged buyout (LBO) transaction MOST typically involves:",
        "option_a": "An IPO of a company funded primarily with equity capital.",
        "option_b": "Acquiring a company using a large proportion of debt financing.",
        "option_c": "Purchasing bonds issued by a distressed company.",
        "correct_answer": "B",
        "explanation_en": "An LBO involves acquiring a target company using a significant portion of debt (leverage), with the company's assets and cash flows used as collateral for the debt.",
        "source": "WIB Internal",
    },
    {
        "topic": "Alternative Investments",
        "subtopic": "Real Estate",
        "difficulty": "medium",
        "question_en": "A Real Estate Investment Trust (REIT) is BEST characterized as:",
        "option_a": "A closed-end fund that trades like a stock and invests in real estate.",
        "option_b": "A mortgage-backed security backed by residential mortgages.",
        "option_c": "A private equity fund focused on commercial property.",
        "correct_answer": "A",
        "explanation_en": "REITs are publicly traded companies that own income-producing real estate. They must distribute at least 90% of taxable income as dividends and are traded on stock exchanges like regular equities.",
        "source": "WIB Internal",
    },
    {
        "topic": "Alternative Investments",
        "subtopic": "Commodities",
        "difficulty": "medium",
        "question_en": "The total return on a commodity futures investment consists of:",
        "option_a": "Spot return, roll return, and collateral return.",
        "option_b": "Dividend yield, price appreciation, and currency return.",
        "option_c": "Carry, price return, and management fee.",
        "correct_answer": "A",
        "explanation_en": "Commodity futures total return = Spot return (change in commodity price) + Roll return (gain/loss from rolling futures contracts) + Collateral return (interest on collateral).",
        "source": "WIB Internal",
    },
    {
        "topic": "Alternative Investments",
        "subtopic": "Hedge Funds",
        "difficulty": "hard",
        "question_en": "A global macro hedge fund strategy MOST likely involves:",
        "option_a": "Taking long/short positions based on relative value between similar securities.",
        "option_b": "Trading currencies, interest rates, and equity indices based on macroeconomic views.",
        "option_c": "Investing in distressed debt of companies near or in bankruptcy.",
        "correct_answer": "B",
        "explanation_en": "Global macro funds take directional positions in currencies, interest rates, commodities, and equity markets based on macroeconomic analysis and forecasts.",
        "source": "WIB Internal",
    },
    # ══════════════════════════════════════════════════════════
    # PORTFOLIO MANAGEMENT  (20 questions)
    # ══════════════════════════════════════════════════════════
    {
        "topic": "Portfolio Management",
        "subtopic": "Modern Portfolio Theory",
        "difficulty": "easy",
        "question_en": "According to modern portfolio theory, diversification reduces:",
        "option_a": "Systematic (market) risk only.",
        "option_b": "Unsystematic (firm-specific) risk only.",
        "option_c": "Both systematic and unsystematic risk.",
        "correct_answer": "B",
        "explanation_en": "Diversification eliminates unsystematic (idiosyncratic) risk through combining uncorrelated assets. Systematic risk (beta risk) cannot be diversified away.",
        "source": "WIB Internal",
    },
    {
        "topic": "Portfolio Management",
        "subtopic": "CAPM",
        "difficulty": "medium",
        "question_en": "According to the Capital Asset Pricing Model (CAPM), the expected return on an asset equals:",
        "option_a": "The risk-free rate plus the asset's beta multiplied by the market risk premium.",
        "option_b": "The market return plus the asset's alpha.",
        "option_c": "The risk-free rate plus a liquidity premium.",
        "correct_answer": "A",
        "explanation_en": "CAPM: E(Ri) = Rf + βi × [E(Rm) - Rf]. The expected return equals the risk-free rate plus a risk premium proportional to systematic risk (beta).",
        "source": "WIB Internal",
    },
    {
        "topic": "Portfolio Management",
        "subtopic": "CAPM",
        "difficulty": "medium",
        "question_en": "A stock with a beta of 1.5 and a market risk premium of 6% will have an expected return (assuming Rf = 3%) closest to:",
        "option_a": "12%",
        "option_b": "9%",
        "option_c": "15%",
        "correct_answer": "A",
        "explanation_en": "CAPM: E(R) = 3% + 1.5 × 6% = 3% + 9% = 12%.",
        "source": "WIB Internal",
    },
    {
        "topic": "Portfolio Management",
        "subtopic": "Efficient Frontier",
        "difficulty": "medium",
        "question_en": "The minimum-variance frontier represents portfolios that:",
        "option_a": "Maximize return for a given level of risk.",
        "option_b": "Minimize risk (variance) for each level of expected return.",
        "option_c": "Offer the highest Sharpe ratio for each level of return.",
        "correct_answer": "B",
        "explanation_en": "The minimum-variance frontier traces all portfolios with the lowest possible variance at each return level. The efficient frontier is the upper portion.",
        "source": "WIB Internal",
    },
    {
        "topic": "Portfolio Management",
        "subtopic": "Investment Policy Statement",
        "difficulty": "medium",
        "question_en": "An Investment Policy Statement (IPS) MUST specify a client's:",
        "option_a": "Exact asset allocation and specific securities to be held.",
        "option_b": "Return objectives and risk tolerance, along with relevant constraints.",
        "option_c": "Expected market returns and benchmark indices.",
        "correct_answer": "B",
        "explanation_en": "The IPS documents client return objectives, risk tolerance, time horizon, liquidity needs, tax concerns, legal constraints, and unique preferences. It guides portfolio construction.",
        "source": "WIB Internal",
    },
    {
        "topic": "Portfolio Management",
        "subtopic": "Behavioral Finance",
        "difficulty": "medium",
        "question_en": "Loss aversion in behavioral finance describes the tendency of investors to:",
        "option_a": "Avoid all investments that have ever generated a loss.",
        "option_b": "Feel the pain of losses more intensely than the pleasure of equivalent gains.",
        "option_c": "Systematically underestimate the probability of large negative outcomes.",
        "correct_answer": "B",
        "explanation_en": "Loss aversion (Kahneman and Tversky) means losses feel approximately twice as powerful psychologically as equivalent gains, causing suboptimal investment decisions.",
        "source": "WIB Internal",
    },
    {
        "topic": "Portfolio Management",
        "subtopic": "Performance Evaluation",
        "difficulty": "hard",
        "question_en": "The Treynor ratio measures portfolio performance as:",
        "option_a": "Excess return per unit of total risk (standard deviation).",
        "option_b": "Excess return per unit of systematic risk (beta).",
        "option_c": "Active return per unit of tracking error.",
        "correct_answer": "B",
        "explanation_en": "Treynor Ratio = (Rp - Rf) / βp. Unlike the Sharpe ratio (which uses total risk), Treynor uses beta — appropriate for well-diversified portfolios.",
        "source": "WIB Internal",
    },
    # Additional questions to reach 220+
    {
        "topic": "Quantitative Methods",
        "subtopic": "Time Value of Money",
        "difficulty": "hard",
        "question_en": "A perpetuity pays $500 per year forever. If the required rate of return is 4%, the present value of the perpetuity is:",
        "option_a": "$10,000",
        "option_b": "$12,500",
        "option_c": "$20,000",
        "correct_answer": "B",
        "explanation_en": "PV of perpetuity = PMT / r = 500 / 0.04 = $12,500.",
        "source": "WIB Internal",
    },
    {
        "topic": "Economics",
        "subtopic": "Monetary Policy",
        "difficulty": "hard",
        "question_en": "Quantitative easing (QE) is a monetary policy tool where the central bank:",
        "option_a": "Raises the reserve requirement ratio to restrict bank lending.",
        "option_b": "Purchases long-term securities to inject liquidity into the financial system.",
        "option_c": "Raises the discount rate to reduce inflation.",
        "correct_answer": "B",
        "explanation_en": "QE involves large-scale asset purchases (typically long-term government bonds or MBS) by the central bank to lower long-term interest rates and stimulate the economy when short-term rates are near zero.",
        "source": "WIB Internal",
    },
    {
        "topic": "Financial Statement Analysis",
        "subtopic": "Revenue Recognition",
        "difficulty": "medium",
        "question_en": "Under IFRS 15, revenue from contracts with customers is recognized when:",
        "option_a": "Cash is received from the customer.",
        "option_b": "The performance obligation is satisfied and control of goods/services transfers to the customer.",
        "option_c": "The contract is signed by both parties.",
        "correct_answer": "B",
        "explanation_en": "IFRS 15 uses a 5-step model. Revenue is recognized when (or as) a performance obligation is satisfied — i.e., when control of the promised good or service transfers to the customer.",
        "source": "WIB Internal",
    },
    {
        "topic": "Fixed Income",
        "subtopic": "Yield Measures",
        "difficulty": "medium",
        "question_en": "The yield-to-maturity (YTM) of a bond assumes that:",
        "option_a": "All coupon payments are reinvested at the bond's coupon rate.",
        "option_b": "All coupon payments are reinvested at the YTM.",
        "option_c": "Coupon payments are spent and not reinvested.",
        "correct_answer": "B",
        "explanation_en": "YTM assumes that all coupon payments are reinvested at the YTM rate. If reinvestment rates differ, the realized return will differ from the YTM.",
        "source": "WIB Internal",
    },
    {
        "topic": "Derivatives",
        "subtopic": "Options",
        "difficulty": "hard",
        "question_en": "According to Black-Scholes option pricing, which factor INCREASES the value of a call option?",
        "option_a": "A decrease in the risk-free rate.",
        "option_b": "An increase in the underlying asset's volatility.",
        "option_c": "A decrease in the time to expiration.",
        "correct_answer": "B",
        "explanation_en": "Higher volatility increases the probability of the option expiring in-the-money, increasing call option value. Vega (sensitivity to volatility) is positive for both calls and puts.",
        "source": "WIB Internal",
    },
    {
        "topic": "Alternative Investments",
        "subtopic": "Private Equity",
        "difficulty": "hard",
        "question_en": "The internal rate of return (IRR) of a private equity fund is best described as:",
        "option_a": "The annualized return based on time-weighted cash flows.",
        "option_b": "The discount rate that makes the net present value of all cash flows equal to zero.",
        "option_c": "The fund's total value divided by paid-in capital.",
        "correct_answer": "B",
        "explanation_en": "IRR is the discount rate at which NPV = 0. In private equity, IRR is calculated on the timing and magnitude of actual cash flows (capital calls and distributions).",
        "source": "WIB Internal",
    },
    {
        "topic": "Equity Investments",
        "subtopic": "Equity Valuation",
        "difficulty": "hard",
        "question_en": "Enterprise Value (EV) is BEST defined as:",
        "option_a": "Market capitalization + Total debt - Cash and equivalents.",
        "option_b": "Market capitalization / Earnings per share.",
        "option_c": "Total assets - Total liabilities.",
        "correct_answer": "A",
        "explanation_en": "EV = Market Cap + Total Debt (including preferred stock) - Cash and Cash Equivalents. It represents the theoretical takeover price of a company.",
        "source": "WIB Internal",
    },
    {
        "topic": "Corporate Issuers",
        "subtopic": "Capital Structure",
        "difficulty": "hard",
        "question_en": "The trade-off theory of capital structure argues that firms balance:",
        "option_a": "The tax benefits of debt against the costs of financial distress.",
        "option_b": "The interest tax shield against equity issuance costs.",
        "option_c": "Retained earnings against new debt issuance.",
        "correct_answer": "A",
        "explanation_en": "The trade-off theory states firms choose leverage to balance the tax shield benefit of debt (interest is tax-deductible) against the increasing probability and costs of financial distress.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard VII — Responsibilities as CFA Member",
        "difficulty": "medium",
        "question_en": "A CFA charterholder who uses the designation in written materials MUST:",
        "option_a": "Spell out 'CFA' in full on first use and use proper notation thereafter.",
        "option_b": "Not use the designation as a noun; it must always be used as an adjective.",
        "option_c": "Obtain annual written permission from CFA Institute.",
        "correct_answer": "B",
        "explanation_en": "The CFA designation must be used as an adjective (e.g., 'John Smith, CFA'), not as a noun or verb. Standard VII(B) governs proper use of the designation.",
        "source": "WIB Internal",
    },
    {
        "topic": "Quantitative Methods",
        "subtopic": "Probability",
        "difficulty": "hard",
        "question_en": "Bayes' theorem is used to:",
        "option_a": "Calculate the probability of two events occurring simultaneously.",
        "option_b": "Update a prior probability based on new information.",
        "option_c": "Determine the expected value of a random variable.",
        "correct_answer": "B",
        "explanation_en": "Bayes' theorem allows updating prior probabilities with new information: P(A|B) = P(B|A) × P(A) / P(B).",
        "source": "WIB Internal",
    },
    {
        "topic": "Economics",
        "subtopic": "Exchange Rates",
        "difficulty": "medium",
        "question_en": "Purchasing Power Parity (PPP) theory states that exchange rates should adjust to:",
        "option_a": "Equalize interest rates across countries.",
        "option_b": "Equalize the price of identical goods across countries.",
        "option_c": "Reflect the difference in current account balances.",
        "correct_answer": "B",
        "explanation_en": "PPP holds that exchange rates adjust so that identical goods cost the same in different countries when prices are expressed in a common currency.",
        "source": "WIB Internal",
    },
    {
        "topic": "Financial Statement Analysis",
        "subtopic": "Cash Flow Statement",
        "difficulty": "hard",
        "question_en": "When using the indirect method for operating cash flows, an increase in accounts receivable is:",
        "option_a": "Added back to net income.",
        "option_b": "Subtracted from net income.",
        "option_c": "Classified as an investing cash outflow.",
        "correct_answer": "B",
        "explanation_en": "An increase in accounts receivable means revenue was recognized but cash was not collected — reducing cash from operations. Under the indirect method, it is subtracted from net income.",
        "source": "WIB Internal",
    },
    {
        "topic": "Portfolio Management",
        "subtopic": "Asset Allocation",
        "difficulty": "medium",
        "question_en": "Strategic asset allocation involves:",
        "option_a": "Making short-term tactical deviations from benchmark weights based on market outlook.",
        "option_b": "Setting long-term target weights for asset classes based on the IPS objectives.",
        "option_c": "Selecting individual securities within each asset class.",
        "correct_answer": "B",
        "explanation_en": "Strategic asset allocation sets long-run target weights consistent with the investor's risk tolerance, return objectives, and investment horizon as stated in the IPS.",
        "source": "WIB Internal",
    },
    {
        "topic": "Fixed Income",
        "subtopic": "Spread Measures",
        "difficulty": "hard",
        "question_en": "The zero-volatility spread (Z-spread) is BEST defined as:",
        "option_a": "The spread over the issuer's benchmark yield at a single maturity.",
        "option_b": "The constant spread added to the spot rate curve to equate the PV of cash flows to the market price.",
        "option_c": "The spread that accounts for the option embedded in a callable bond.",
        "correct_answer": "B",
        "explanation_en": "The Z-spread is the constant basis point spread added to the entire Treasury (or benchmark) spot rate curve so that the discounted cash flows equal the bond's market price.",
        "source": "WIB Internal",
    },
    {
        "topic": "Equity Investments",
        "subtopic": "Equity Valuation",
        "difficulty": "medium",
        "question_en": "A company has an EV/EBITDA multiple of 8x and EBITDA of $50 million. If net debt is $100 million and shares outstanding are 20 million, the equity value per share is:",
        "option_a": "$15",
        "option_b": "$20",
        "option_c": "$25",
        "correct_answer": "A",
        "explanation_en": "EV = 8 × $50M = $400M. Equity Value = EV - Net Debt = $400M - $100M = $300M. Per share = $300M / 20M = $15.",
        "source": "WIB Internal",
    },
    {
        "topic": "Derivatives",
        "subtopic": "Futures",
        "difficulty": "hard",
        "question_en": "The cost of carry model for a forward price on a non-dividend-paying stock is expressed as:",
        "option_a": "F = S × e^(rT) for continuous compounding.",
        "option_b": "F = S / (1 + r)^T.",
        "option_c": "F = S + D - r × T.",
        "correct_answer": "A",
        "explanation_en": "For a non-dividend-paying stock: F = S × e^(rT) (continuous) or F = S × (1+r)^T (discrete). The forward price equals the spot price compounded at the risk-free rate.",
        "source": "WIB Internal",
    },
    {
        "topic": "Alternative Investments",
        "subtopic": "Infrastructure",
        "difficulty": "medium",
        "question_en": "Infrastructure investments are characterized by:",
        "option_a": "High liquidity and low barriers to entry.",
        "option_b": "Long-lived assets, stable cash flows, and monopolistic characteristics.",
        "option_c": "High correlation with public equity markets and short investment horizons.",
        "correct_answer": "B",
        "explanation_en": "Infrastructure assets (toll roads, airports, utilities) typically have long lives, generate stable cash flows (often inflation-linked), and operate in monopolistic or oligopolistic markets.",
        "source": "WIB Internal",
    },
    {
        "topic": "Corporate Issuers",
        "subtopic": "Working Capital",
        "difficulty": "medium",
        "question_en": "A decrease in the cash conversion cycle (CCC) indicates that a firm is:",
        "option_a": "Taking longer to convert investments in inventory into cash.",
        "option_b": "More efficiently managing its working capital.",
        "option_c": "Experiencing deteriorating liquidity.",
        "correct_answer": "B",
        "explanation_en": "CCC = Days Inventory Outstanding + Days Sales Outstanding - Days Payable Outstanding. A shorter CCC means the firm converts resources to cash more quickly, improving working capital efficiency.",
        "source": "WIB Internal",
    },
    {
        "topic": "Economics",
        "subtopic": "GDP and Business Cycles",
        "difficulty": "medium",
        "question_en": "In the expenditure approach to GDP, investment (I) includes:",
        "option_a": "Purchases of financial assets such as stocks and bonds.",
        "option_b": "Business fixed investment, residential investment, and change in inventories.",
        "option_c": "Government transfer payments and subsidies.",
        "correct_answer": "B",
        "explanation_en": "GDP investment component = business fixed investment (plant, equipment) + residential investment (housing) + change in inventories. Financial asset purchases are excluded.",
        "source": "WIB Internal",
    },
    {
        "topic": "Financial Statement Analysis",
        "subtopic": "Earnings Quality",
        "difficulty": "hard",
        "question_en": "Which of the following indicates HIGH earnings quality?",
        "option_a": "Operating cash flow significantly lower than reported net income.",
        "option_b": "Operating cash flow closely tracking reported net income over time.",
        "option_c": "Large recurring special charges every year.",
        "correct_answer": "B",
        "explanation_en": "High earnings quality is evidenced by operating cash flows that closely track net income. A large gap (with income much higher than CFO) may indicate aggressive accruals.",
        "source": "WIB Internal",
    },
    {
        "topic": "Ethics & Professional Standards",
        "subtopic": "Standard III — Duties to Clients",
        "difficulty": "hard",
        "question_en": "Under Standard III(C) – Suitability, a manager must:",
        "option_a": "Select securities with the highest expected return for all clients.",
        "option_b": "Ensure each investment is suitable in the context of the total portfolio and the client's IPS.",
        "option_c": "Invest client funds in line with the manager's own risk preferences.",
        "correct_answer": "B",
        "explanation_en": "Standard III(C) requires that investment recommendations be suitable in the context of the client's total portfolio, IPS, risk tolerance, time horizon, and financial needs.",
        "source": "WIB Internal",
    },
    {
        "topic": "Quantitative Methods",
        "subtopic": "Technical Analysis",
        "difficulty": "easy",
        "question_en": "Technical analysts primarily use:",
        "option_a": "Financial statements to value securities.",
        "option_b": "Historical price and volume data to identify patterns and forecast price movements.",
        "option_c": "Macroeconomic data to time market cycles.",
        "correct_answer": "B",
        "explanation_en": "Technical analysis studies historical market data (primarily price and volume) to identify patterns and trends that may predict future price movements.",
        "source": "WIB Internal",
    },
    {
        "topic": "Portfolio Management",
        "subtopic": "Risk Management",
        "difficulty": "hard",
        "question_en": "Value at Risk (VaR) at the 95% confidence level over a 1-day horizon means that:",
        "option_a": "The portfolio will lose exactly this amount 5% of the time.",
        "option_b": "The maximum loss will not exceed this amount in 95% of cases over a 1-day period.",
        "option_c": "The expected loss per day equals this amount.",
        "correct_answer": "B",
        "explanation_en": "VaR at 95% confidence = the maximum loss that will not be exceeded on 95% of days. Equivalently, there is a 5% probability that the loss will exceed the VaR.",
        "source": "WIB Internal",
    },
    {
        "topic": "Fixed Income",
        "subtopic": "Duration",
        "difficulty": "hard",
        "question_en": "A bond portfolio has a modified duration of 6.0. If yields increase by 50 basis points, the approximate percentage change in portfolio value is:",
        "option_a": "+3.0%",
        "option_b": "-3.0%",
        "option_c": "-6.0%",
        "correct_answer": "B",
        "explanation_en": "%ΔP ≈ -Modified Duration × ΔYield = -6.0 × 0.0050 = -0.030 = -3.0%.",
        "source": "WIB Internal",
    },
    {
        "topic": "Equity Investments",
        "subtopic": "Security Markets",
        "difficulty": "medium",
        "question_en": "A primary market transaction is BEST described as:",
        "option_a": "The trading of previously issued securities between investors.",
        "option_b": "The sale of newly issued securities by an issuer to investors.",
        "option_c": "A secondary offering of shares by existing shareholders.",
        "correct_answer": "B",
        "explanation_en": "Primary market transactions involve the issuance of new securities (IPO, follow-on offerings) where proceeds go to the issuer. Secondary market transactions are between investors.",
        "source": "WIB Internal",
    },
    {
        "topic": "Corporate Issuers",
        "subtopic": "Capital Budgeting",
        "difficulty": "hard",
        "question_en": "When computing the NPV of a project, which of the following should be EXCLUDED from the cash flow analysis?",
        "option_a": "Incremental revenues generated by the project.",
        "option_b": "Sunk costs incurred before the investment decision.",
        "option_c": "Cannibalization effects on existing product lines.",
        "correct_answer": "B",
        "explanation_en": "Sunk costs are past, irreversible costs that are not affected by the current decision. They should be excluded from NPV analysis. Only incremental (future) cash flows are relevant.",
        "source": "WIB Internal",
    },
    {
        "topic": "Derivatives",
        "subtopic": "Options",
        "difficulty": "medium",
        "question_en": "An investor buys a protective put. This strategy involves:",
        "option_a": "Buying a stock and buying a put option on that stock.",
        "option_b": "Selling a stock short and buying a call option.",
        "option_c": "Buying a bond and selling a call option.",
        "correct_answer": "A",
        "explanation_en": "A protective put combines a long stock position with a long put option, providing downside protection while retaining upside participation.",
        "source": "WIB Internal",
    },
    {
        "topic": "Alternative Investments",
        "subtopic": "Hedge Funds",
        "difficulty": "medium",
        "question_en": "Survivorship bias in hedge fund databases MOST likely causes:",
        "option_a": "Underestimation of average fund returns.",
        "option_b": "Overestimation of average fund returns.",
        "option_c": "Accurate estimation of fund returns since databases are updated regularly.",
        "correct_answer": "B",
        "explanation_en": "Survivorship bias occurs when failed/closed funds are removed from databases. Remaining funds have survived by performing better, overstating the average return of the hedge fund universe.",
        "source": "WIB Internal",
    },
    {
        "topic": "Portfolio Management",
        "subtopic": "Modern Portfolio Theory",
        "difficulty": "hard",
        "question_en": "Two assets are perfectly negatively correlated (ρ = -1). The minimum variance portfolio of these two assets has a standard deviation of:",
        "option_a": "The average of the two individual standard deviations.",
        "option_b": "Zero.",
        "option_c": "The lower of the two individual standard deviations.",
        "correct_answer": "B",
        "explanation_en": "When correlation = -1, two assets can be combined in specific proportions to eliminate all portfolio risk (variance = 0), achieving a risk-free portfolio.",
        "source": "WIB Internal",
    },
]
